#5. Programa que pida cinco palabras y muestre una frase con las cinco. Modifica el código para que entre palabra y palabra haya una coma.
palabra1 = input("INTRODUCE LA PRIMERA PALABRA: ")
palabra2 = input("INTRODUCE LA SEGUNDA PALABRA: ")
palabra3 = input("INTRODUCE LA TERCERA PALABRA: ")
palabra4 = input("INTRODUCE LA CUARTA PALABRA: ")
palabra5 = input("INTRODUCE LA QUINTA PALABRA: ")

frase = palabra1 + ", " + palabra2 + ", " + palabra3 + ", " + palabra4 + ", " + palabra5
print("LA FRASE ES:", frase)